### ISSUE TITLE
Other caching strategies?

### ISSUE THREAD

**Issue by jmatsushita** [apollographql/GitHunt-API#116]
Hi there,

Hope this is the right place to post this question, I guess that the`tools-docs` repo was another candidate. I'm wondering whether it would make sense to document and offer a reference implementation for other cache strategies than per-request caching?

For instance when there is a good portion of data that is not user specific then it would be great to have a sense of how to implement in Apollo something like:
 - Having a shared global cache in Dataloader (in addition to a per-request cache if needed).
 - Invalidate the Dataloader cache (via `clear(key)`) in sync with GraphQL Mutation invalidation.
 - Use subscriptions to invalidate other client caches.

It seems that the pieces could fit together, but it seems it would be very beneficial to have the apollostack teams' take on this, maybe as part of a `GitHunt-API` example? Or at least some breadcrumbs :)

Cheers,

Jun

**Comment by helfer** [comment]
@jmatsushita yeah, I think that's a really good point. I think @jbaxleyiii has built some extensive cross-request caching into their app, so maybe he has some input on this?

I'd love to tell you that we have all the answers, but a lot of the wisdom here comes from the community and people like you, who've tried things and shared them with others. If someone has done it and shared it with the community, then it's likely that we know about it, but I don't think anyone has tried this and publicly written about it yet, so you could be the first to do it!

Everything you wrote sounds 100% sensible to me, so if I were you, I'd just go ahead and implement the first two points and then see how far that gets me.

**Comment by stubailo** [comment]
I'm pretty certain this repository isn't the right place to have this discussion, though - maybe graphql-server?
