### ISSUE TITLE
Websockets for subscriptions not working?

### ISSUE THREAD

**Issue by ayafor** [apollographql/GitHunt-API#191]
Hi,

Not sure what I'm doing wrong here, but I:
 - setup and ran the latest from this repo as described in the "Running the Server" section
 - ran the api
 - setup and ran the GitHunt-React example.

I see this error: WebSocket connection to 'ws://localhost:3010/' failed: Connection closed before receiving a handshake response.

I tried these repos after struggling in vain to connect with my own app, following the examples. I don't know if I'm missing something.

I'm using Chrome on a macOS Sierra

**Comment by ayafor** [comment]
OK,

Not sure if the documentation is wrong or not, but to fix this I had to do things slightly different:

new SubscriptionServer(
    {
      subscriptionManager,
      ....
   },
   {
     path: '/subscriptions', // <-- instead of 'subscriptions'
     server,
   }

...and on the client, I used url 'ws://localhost:3010/subscriptions' instead of 'ws://localhost:3010'

Thanks

**Comment by Urigo** [comment]
yes, I've added that fix in the PR here - https://github.com/apollographql/GitHunt-API/pull/187
Sorry about that
