### ISSUE TITLE
[Code Explanation] Does the schema specify return types?

### ISSUE THREAD

**Issue by servermeta** [apollographql/GitHunt-API#216]
In this page:

https://github.com/apollographql/GitHunt-API/blob/master/api/schema.js

at line 33 it seems like you are specifying a return type for the query. Is this a thing? I couldn't find any documentation elsewhere.

**Comment by stubailo** [comment]
Yeah, you can learn about it on GraphQL.org: http://graphql.org/learn/schema/#object-types-and-fields

We actually wrote that page on GraphQL so we're trying not to duplicate it in the docs here. But we should definitely add links to that for people who are starting out with GraphQL.

**Comment by stubailo** [comment]
(Let me know if that's enough info, happy to help more)

**Comment by servermeta** [comment]
Thank you @stubailo , you are very helpful as always. 

So I already read that page, and I knew that I could specify types for the inputs and fields, but it's the first time I see it used on the return type. 

Is it mentioned somewhere in the docs? Or is it implicit, in the sense that since we are using a flow-like syntax, then we can specify also return types?

Another, unrelated question: why don't you use the apollo section on the meteor forum as the official newbie discussion board?
