### ISSUE TITLE
Can't debug with the current launch.json in windows

### ISSUE THREAD

**Issue by NathanielMalca** [apollographql/GitHunt-API#92]
Hi,

Please add the Windows launch file to the repository since it currently not debuggable  in windows.

Thanks

**Comment by intellix** [comment]
What error are you getting? I was getting an error about sqlite3 with me using yarn and the lock file being quite out of date. Using npm install worked for me

**Comment by NathanielMalca** [comment]
this is the output i'm getting:

node_modules/.bin/nodemon --debug-brk=16812 api\index.js --watch api --exec node_modules/.bin/babel-node

btw, on linux it works just fine :/

**Comment by helfer** [comment]
Closing since there hasn't been any activity here for a long time. If other people have the same problem, please tune in!
